//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timetabling06.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class building
    {
        public building()
        {
            this.rooms = new HashSet<room>();
        }
    
        public string code { get; set; }
        public string name { get; set; }
        public string park { get; set; }
    
        public virtual ICollection<room> rooms { get; set; }
    }
}
