//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timetabling06.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class team06Entities : DbContext
    {
        public team06Entities()
            : base("name=team06Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<announcement> announcements { get; set; }
        public virtual DbSet<building> buildings { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<facility> facilities { get; set; }
        public virtual DbSet<module> modules { get; set; }
        public virtual DbSet<request> requests { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<room_request> room_request { get; set; }
        public virtual DbSet<round> rounds { get; set; }
        public virtual DbSet<semester> semesters { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
        public virtual DbSet<weeks_request> weeks_request { get; set; }
    }
}
