//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timetabling06.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public department()
        {
            this.modules = new HashSet<module>();
            this.requests = new HashSet<request>();
            this.rooms = new HashSet<room>();
            this.staffs = new HashSet<staff>();
        }
    
        public string code { get; set; }
        public string name { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<module> modules { get; set; }
        public virtual ICollection<request> requests { get; set; }
        public virtual ICollection<room> rooms { get; set; }
        public virtual ICollection<staff> staffs { get; set; }
    }
}
