//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timetabling06.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class facility
    {
        public facility()
        {
            this.requests = new HashSet<request>();
            this.rooms = new HashSet<room>();
        }
    
        public short facilityID { get; set; }
        public string facilityName { get; set; }
    
        public virtual ICollection<request> requests { get; set; }
        public virtual ICollection<room> rooms { get; set; }
    }
}
