//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timetabling06.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class module
    {
        public module()
        {
            this.requests = new HashSet<request>();
            this.staffs = new HashSet<staff>();
        }
    
        public string moduleCode { get; set; }
        public string deptCode { get; set; }
        public string moduleTitle { get; set; }
    
        public virtual department department { get; set; }
        public virtual ICollection<request> requests { get; set; }
        public virtual ICollection<staff> staffs { get; set; }
    }
}
