//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timetabling06.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class room_request
    {
        public int requestID { get; set; }
        public string buildingCode { get; set; }
        public string roomNumber { get; set; }
        public int class_size { get; set; }
        public int priority { get; set; }
    
        public virtual request request { get; set; }
        public virtual room room { get; set; }
    }
}
