//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timetabling06.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class room
    {
        public room()
        {
            this.room_request = new HashSet<room_request>();
            this.facilities = new HashSet<facility>();
            this.requests = new HashSet<request>();
        }
    
        public string roomNumber { get; set; }
        public string buildingCode { get; set; }
        public string roomType { get; set; }
        public string roomStructure { get; set; }
        public int capacity { get; set; }
        public string belongsTo { get; set; }
    
        public virtual building building { get; set; }
        public virtual department department { get; set; }
        public virtual ICollection<room_request> room_request { get; set; }
        public virtual ICollection<facility> facilities { get; set; }
        public virtual ICollection<request> requests { get; set; }
    }
}
