//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timetabling06.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class semester
    {
        public semester()
        {
            this.rounds = new HashSet<round>();
        }
    
        public int semester1 { get; set; }
        public int year { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public short weeks { get; set; }
    
        public virtual ICollection<round> rounds { get; set; }
    }
}
