//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timetabling06.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public staff()
        {
            this.modules = new HashSet<module>();
        }
    
        public int staffID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string deptCode { get; set; }
    
        public virtual department department { get; set; }
        public virtual ICollection<module> modules { get; set; }
    }
}
